import styles from "../styles/Home.module.css";
import Head from "next/head";
import { Header } from "../components/Header";
import { Counter } from "../components/Counter";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.App}>
        <img
          src="/next.svg"
          className={styles.appLogo}
          alt="logo"
          width={180}
          height={37}
        />
        <Header />
        <Counter />
      </div>
    </>
  );
}
